name: Report to Sonar
on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - master
    paths:
      - .github/workflows/PR_Deploy.yml

jobs:
  call:
    uses: bancodebogota/bbog-dr-pipeline/.github/workflows/requirements_services_python.yml@master
    with:
      work-dir: "./app"
      language: "python"
      project-name: ""
      path-name: "app"
    secrets:
      DIG_READER_GITHUB_USER: ${{ secrets.DIG_READER_GITHUB_USER }}
      DIG_READER_GITHUB_ACCESS_TOKEN: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
      SONAR_CLOUD_ORG : ${{secrets.SONAR_CLOUD_ORG}}
      SONAR_CLOUD_TOKEN : ${{secrets.SONAR_CLOUD_TOKEN}}
