name: Deploy QA

on:
  push:
    branches: qa

jobs:
  deploy:
    name: Upload file to bucket in qa
    runs-on: ubuntu-latest
    environment: qa
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.DIG_READER_GITHUB_ACCESS_TOKEN}}

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v0
        with:
          project_id: 'bdb-gcp-qa-cds-idt'
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: "Temorary Folder"
        run: mkdir feature-storage-functions

      - name: "Create Zip"
        run: |
          zip -r feature_storage.zip app/*

      - name: "Move file zip to folder feature-storage-functions"
        run: mv feature_storage.zip feature-storage-functions

      - name: "Copy main.py"
        run: cp ./app/main.py ./feature-storage-functions/main_feature_storage.py

      - name: Load File
        id: 'upload-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: "feature-storage-functions/"
          destination: "bdb-gcp-qa-cds-idt-mlops/model/propensity-model-598/input"
          gzip: false