name: Report to Sonar
on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - qa
    paths:
      - .github/workflows/QA_Deploy.yml

jobs:
  call:
    uses: bancodebogota/bbog-dr-pipeline/.github/workflows/requirements_services_python.yml@master
    with:
      work-dir: "./app"
      language: "python"
      project-name: ""
      path-name: "app"
    secrets:
      DIG_READER_GITHUB_USER: ${{ secrets.DIG_READER_GITHUB_USER }}
      DIG_READER_GITHUB_ACCESS_TOKEN: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
      SONAR_CLOUD_ORG : ${{secrets.SONAR_CLOUD_ORG}}
      SONAR_CLOUD_TOKEN : ${{secrets.SONAR_CLOUD_TOKEN}}

  deploy_qa:
    name: Upload file to bucket in qa
    ##needs: [call]
    runs-on: ubuntu-latest
    environment: qa
    permissions:
        contents: 'read'
        id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.DIG_READER_GITHUB_ACCESS_TOKEN}}

      - name: "Temorary Folder"
        run: mkdir python

      - name: "Create Zip"
        run: |
          zip -r feature_storage.zip app/*

      - name: "Move file zip to folder python"
        run: mv feature_storage.zip python

      - name: "Copy main_feature_storage.py"
        run: cp ./app/main_feature_storage.py ./python/main_feature_storage.py

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v0
        with:
            project_id: 'bdb-gcp-qa-cds-idt'
            workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
            service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Load File
        id: 'upload-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: "python/"
          destination: "bdb-gcp-qa-cds-idt-mlops/model/propensity-model-598/input/feature-storage-functions"