name: Requirements

on:
  pull_request:
    branches: [qa, staging, master]

jobs:
  requirements-backend:
    uses: bancodebogota/bbog-dr-pipeline/.github/workflows/requirements_python_backend.yml@releasev1
    with:
      work-dir: "./app"
      language: "python"
      project-name: ""
      path-name: "app"
      path-environments-variables: ""
    secrets:
      DIG_READER_GITHUB_USER: ${{ secrets.DIG_READER_GITHUB_USER }}
      DIG_READER_GITHUB_ACCESS_TOKEN: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
      SONAR_CLOUD_ORG : ${{secrets.SONAR_CLOUD_ORG}}
      SONAR_CLOUD_TOKEN : ${{secrets.SONAR_CLOUD_TOKEN}}
